spring:
  application:
    name: orm-cache
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace

  flyway:
    enabled: true
    locations: [ "classpath:/db/migration" ]
    out-of-order: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orm-cache?useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 300
      minimumIdle: 10
      connection-test-query: "select 1"